/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户注册（学生/教师） */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退出登录 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新 Access Token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户信息 */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/chat/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新建聊天会话 */
        post: operations["createChatSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取聊天会话列表 */
        get: operations["listChatSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/chat/session/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取会话详情 */
        get: operations["getChatSessionDetail"];
        put?: never;
        post?: never;
        /** 删除会话（软删除） */
        delete: operations["deleteChatSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/chat/session/{sessionId}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 向会话发送消息（支持 SSE） */
        post: operations["sendChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/exercise/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取练习题列表 */
        get: operations["listExerciseQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/exercise/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交练习答案并自动判分 */
        post: operations["submitExerciseAnswers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/exercise/{recordId}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看练习解析 */
        get: operations["getExerciseAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/exercise/wrong-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取错题本 */
        get: operations["listWrongQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/exercise/wrong-questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 从错题本移除（标记已掌握） */
        delete: operations["removeWrongQuestion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/exercise/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取做题记录 */
        get: operations["listExerciseRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/ai-questions/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 生成 AI 个性化题目 */
        post: operations["generateAiQuestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/ai-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 AI 出题历史 */
        get: operations["listAiQuestionSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/ai-questions/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交 AI 题目答案 */
        post: operations["submitAiQuestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/ai-questions/{recordId}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 AI 题目解析 */
        get: operations["getAiQuestionAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/knowledge/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取知识库文档列表 */
        get: operations["listKnowledgeDocuments"];
        put?: never;
        /** 上传知识库文档 */
        post: operations["uploadKnowledgeDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/knowledge/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除知识库文档并级联删除向量 */
        delete: operations["deleteKnowledgeDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/plans/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 生成 AI 教案 */
        post: operations["generateLessonPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取教案列表 */
        get: operations["listLessonPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新教案 */
        put: operations["updateLessonPlan"];
        post?: never;
        /** 删除教案 */
        delete: operations["deleteLessonPlan"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/plans/{planId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出教案 */
        get: operations["exportLessonPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/plans/{planId}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 生成教案分享链接 */
        post: operations["shareLessonPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/plans/shared/{shareToken}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 通过分享令牌访问教案 */
        get: operations["getSharedLessonPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/students/{studentId}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取学生学情分析 */
        get: operations["getStudentAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建教师建议 */
        post: operations["createTeacherSuggestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户列表 */
        get: operations["listUsers"];
        put?: never;
        /** 创建用户 */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新用户状态或角色 */
        patch: operations["patchUser"];
        trace?: never;
    };
    "/admin/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取资源列表（教案/题库/文档） */
        get: operations["listResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/resources/{resourceId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载资源 */
        get: operations["downloadResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取审计日志 */
        get: operations["listAudits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 平台指标看板 */
        get: operations["getAdminDashboardMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 统一响应包装。具体接口通过 allOf 指定 data 类型。 */
        ApiResponse: {
            code: number;
            message: string;
            /** @description 具体业务数据（由各接口 Schema 定义） */
            data?: unknown;
            traceId?: string;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description 分页包装，所有分页接口的 data 字段共用此结构。 */
        PagedData: {
            /** @description 当前页数据列表 */
            content: unknown[];
            /** @description 当前页码（从 1 开始） */
            page: number;
            /** @description 每页大小 */
            size: number;
            /**
             * Format: int64
             * @description 总记录数
             */
            totalElements: number;
            /** @description 总页数 */
            totalPages: number;
        };
        /** @description 用户信息（对外展示） */
        UserVO: {
            /** Format: uuid */
            id?: string;
            username?: string;
            /**
             * @description 枚举定义见 04-领域模型 §5
             * @enum {string}
             */
            role?: "STUDENT" | "TEACHER" | "ADMIN";
            /**
             * @description 枚举定义见 04-领域模型 §5
             * @enum {string}
             */
            status?: "ACTIVE" | "DISABLED";
            email?: string;
            phone?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description 登录成功返回 */
        LoginData: {
            accessToken: string;
            refreshToken: string;
            user: components["schemas"]["UserVO"];
        };
        /** @description 刷新 token 返回 */
        RefreshData: {
            accessToken: string;
            refreshToken: string;
        };
        /** @description 聊天会话 */
        ChatSessionVO: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            studentId?: string;
            title?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description 聊天会话详情（含消息列表） */
        ChatSessionDetailVO: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** Format: date-time */
            createdAt?: string;
            messages?: components["schemas"]["ChatMessageVO"][];
        };
        /** @description 聊天消息 */
        ChatMessageVO: {
            /** Format: uuid */
            id?: string;
            /**
             * @description 枚举定义见 04-领域模型 §5
             * @enum {string}
             */
            role?: "USER" | "ASSISTANT";
            content?: string;
            citations?: components["schemas"]["CitationVO"][] | null;
            tokenUsage?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description AI 回答引用来源 */
        CitationVO: {
            /** Format: uuid */
            documentId?: string;
            filename?: string;
            chunkIndex?: number;
            /** @description 引用片段文本 */
            content?: string;
            /**
             * Format: float
             * @description 相似度得分
             */
            score?: number;
        };
        /** @description 发送消息后的完整回复 */
        ChatReplyVO: {
            userMessage?: components["schemas"]["ChatMessageVO"];
            assistantMessage?: components["schemas"]["ChatMessageVO"];
        };
        /** @description 题目 */
        QuestionVO: {
            /** Format: uuid */
            id?: string;
            subject?: string;
            /**
             * @description 枚举定义见 04-领域模型 §5
             * @enum {string}
             */
            questionType?: "SINGLE_CHOICE" | "MULTIPLE_CHOICE" | "TRUE_FALSE" | "SHORT_ANSWER";
            /**
             * @description 枚举定义见 04-领域模型 §5
             * @enum {string}
             */
            difficulty?: "EASY" | "MEDIUM" | "HARD";
            content?: string;
            options?: {
                [key: string]: string;
            } | null;
            correctAnswer?: string;
            analysis?: string | null;
            knowledgePoints?: string[] | null;
            score?: number;
            /**
             * @description 枚举定义见 04-领域模型 §5
             * @enum {string}
             */
            source?: "MANUAL" | "AI_GENERATED";
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description 做题提交结果 */
        ExerciseResultVO: {
            /** Format: uuid */
            recordId?: string;
            totalQuestions?: number;
            correctCount?: number;
            totalScore?: number;
            items?: components["schemas"]["ExerciseResultItemVO"][];
        };
        /** @description 做题结果明细 */
        ExerciseResultItemVO: {
            /** Format: uuid */
            questionId?: string;
            userAnswer?: string;
            correctAnswer?: string;
            isCorrect?: boolean;
            score?: number;
        };
        /** @description 做题解析 */
        ExerciseAnalysisVO: {
            /** Format: uuid */
            recordId?: string;
            items?: components["schemas"]["ExerciseAnalysisItemVO"][];
        };
        /** @description 逐题解析 */
        ExerciseAnalysisItemVO: {
            /** Format: uuid */
            questionId?: string;
            /** @description 题干 */
            content?: string;
            userAnswer?: string;
            correctAnswer?: string;
            isCorrect?: boolean;
            analysis?: string | null;
            knowledgePoints?: string[] | null;
            /** @description 教师建议（若存在） */
            teacherSuggestion?: string | null;
        };
        /** @description 错题本条目 */
        WrongBookEntryVO: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            questionId?: string;
            question?: components["schemas"]["QuestionVO"];
            wrongCount?: number;
            /** Format: date-time */
            lastWrongTime?: string;
            /**
             * @description 枚举定义见 04-领域模型 §5
             * @enum {string}
             */
            status?: "ACTIVE" | "MASTERED";
        };
        /** @description 做题历史记录 */
        ExerciseRecordVO: {
            /** Format: uuid */
            id?: string;
            subject?: string | null;
            totalQuestions?: number;
            correctCount?: number;
            totalScore?: number;
            /** @description 耗时（秒） */
            timeSpent?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description AI 出题会话 */
        AiQuestionSessionVO: {
            /** Format: uuid */
            id?: string;
            subject?: string;
            /** @enum {string|null} */
            difficulty?: "EASY" | "MEDIUM" | "HARD" | null;
            questionCount?: number;
            completed?: boolean;
            /**
             * Format: float
             * @description 正确率（0-100）
             */
            correctRate?: number | null;
            score?: number | null;
            /** Format: date-time */
            generatedAt?: string;
        };
        /** @description AI 出题生成结果 */
        AiQuestionGenerateResultVO: {
            /** Format: uuid */
            sessionId?: string;
            questions?: components["schemas"]["QuestionVO"][];
        };
        /** @description AI 题提交结果 */
        AiQuestionResultVO: {
            /** Format: uuid */
            recordId?: string;
            /** Format: uuid */
            sessionId?: string;
            totalQuestions?: number;
            correctCount?: number;
            totalScore?: number;
            items?: components["schemas"]["ExerciseResultItemVO"][];
        };
        /** @description AI 题解析 */
        AiQuestionAnalysisVO: {
            /** Format: uuid */
            recordId?: string;
            items?: components["schemas"]["ExerciseAnalysisItemVO"][];
        };
        /** @description 知识库文档 */
        DocumentVO: {
            /** Format: uuid */
            id?: string;
            filename?: string;
            fileType?: string;
            /** Format: int64 */
            fileSize?: number;
            /**
             * @description 状态机定义见 04-领域模型 §3.1
             * @enum {string}
             */
            status?: "UPLOADING" | "PARSING" | "EMBEDDING" | "READY" | "FAILED";
            errorMessage?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description 教案 */
        LessonPlanVO: {
            /** Format: uuid */
            id?: string;
            topic?: string;
            gradeLevel?: string;
            durationMins?: number;
            /** @description Markdown 教案内容 */
            contentMd?: string;
            isShared?: boolean;
            shareToken?: string | null;
            /** Format: date-time */
            sharedAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description 教案分享结果 */
        ShareResultVO: {
            /** Format: uuid */
            planId?: string;
            shareToken?: string;
            shareUrl?: string;
        };
        /** @description 学生学情分析 */
        StudentAnalyticsVO: {
            /** Format: uuid */
            studentId?: string;
            username?: string;
            /** @description 总做题次数 */
            totalExercises?: number;
            /** @description 总题目数 */
            totalQuestions?: number;
            /** @description 总正确数 */
            correctCount?: number;
            /**
             * Format: float
             * @description 平均分
             */
            averageScore?: number;
            /** @description 当前错题本题数 */
            wrongBookCount?: number;
            /** @description 高频错题知识点 */
            topWeakPoints?: {
                knowledgePoint?: string;
                wrongCount?: number;
            }[];
        };
        /** @description 教师建议 */
        TeacherSuggestionVO: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            teacherId?: string;
            /** Format: uuid */
            studentId?: string;
            /** Format: uuid */
            questionId?: string | null;
            knowledgePoint?: string | null;
            suggestion?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description 审计日志 */
        AuditLogVO: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            actorId?: string;
            actorRole?: string;
            action?: string;
            resourceType?: string;
            resourceId?: string;
            detail?: Record<string, never> | null;
            ip?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description 管理端看板指标 */
        DashboardMetricsVO: {
            totalUsers?: number;
            totalStudents?: number;
            totalTeachers?: number;
            totalChatSessions?: number;
            totalExerciseRecords?: number;
            totalDocuments?: number;
            totalKnowledgeChunks?: number;
            totalLessonPlans?: number;
        };
        /** @description 管理端资源列表项 */
        AdminResourceVO: {
            /** Format: uuid */
            resourceId?: string;
            /** @enum {string} */
            resourceType?: "LESSON_PLAN" | "QUESTION" | "DOCUMENT";
            /** @description 资源标题（教案 topic / 题目 content 摘要 / 文档 filename） */
            title?: string;
            /** Format: uuid */
            creatorId?: string;
            creatorUsername?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        RegisterRequest: {
            username: string;
            password: string;
            /** Format: email */
            email?: string;
            phone?: string;
            /**
             * @description 枚举定义见 04-领域模型 §5
             * @enum {string}
             */
            role: "STUDENT" | "TEACHER";
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        ChatSendRequest: {
            message: string;
        };
        ExerciseSubmitRequest: {
            answers: {
                /** Format: uuid */
                questionId: string;
                userAnswer: string;
            }[];
        };
        AiQuestionGenerateRequest: {
            count: number;
            subject: string;
            /**
             * @description 枚举定义见 04-领域模型 §5
             * @enum {string}
             */
            difficulty?: "EASY" | "MEDIUM" | "HARD";
            conceptTags?: string[];
        };
        AiQuestionSubmitRequest: {
            /** Format: uuid */
            sessionId: string;
            answers: {
                /** Format: uuid */
                questionId: string;
                userAnswer: string;
            }[];
        };
        PlanGenerateRequest: {
            topic: string;
            gradeLevel: string;
            durationMins: number;
        };
        PlanUpdateRequest: {
            contentMd: string;
        };
        TeacherSuggestionRequest: {
            /** Format: uuid */
            studentId: string;
            /** Format: uuid */
            questionId?: string;
            knowledgePoint?: string;
            suggestion: string;
        };
        AdminUserCreateRequest: {
            username: string;
            password: string;
            /**
             * @description 枚举定义见 04-领域模型 §5
             * @enum {string}
             */
            role: "STUDENT" | "TEACHER" | "ADMIN";
            /** Format: email */
            email?: string;
            phone?: string;
        };
        AdminUserPatchRequest: {
            /**
             * @description 枚举定义见 04-领域模型 §5
             * @enum {string}
             */
            role?: "STUDENT" | "TEACHER" | "ADMIN";
            /**
             * @description 枚举定义见 04-领域模型 §5
             * @enum {string}
             */
            status?: "ACTIVE" | "DISABLED";
        };
    };
    responses: {
        /** @description 请求参数错误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 400,
                 *       "message": "参数错误",
                 *       "data": null,
                 *       "traceId": "trace-xxx",
                 *       "timestamp": "2026-02-26T10:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description 未认证或 token 失效 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 401,
                 *       "message": "未认证",
                 *       "data": null,
                 *       "traceId": "trace-xxx",
                 *       "timestamp": "2026-02-26T10:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description 无权限 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 403,
                 *       "message": "无权限访问",
                 *       "data": null,
                 *       "traceId": "trace-xxx",
                 *       "timestamp": "2026-02-26T10:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 404,
                 *       "message": "资源不存在",
                 *       "data": null,
                 *       "traceId": "trace-xxx",
                 *       "timestamp": "2026-02-26T10:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
    };
    parameters: {
        Page: number;
        Size: number;
        SessionId: string;
        RecordId: string;
        QuestionId: string;
        DocumentId: string;
        PlanId: string;
        StudentId: string;
        UserId: string;
        ResourceId: string;
        /** @description 幂等键（建议 UUID），用于防止重复提交导致的重复写入 */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功。data → UserVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功。data → LoginData（含 accessToken、refreshToken、user） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 退出成功。data → null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 刷新成功。data → RefreshData */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 获取成功。data → UserVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createChatSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 创建成功。data → ChatSessionVO */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    listChatSessions: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 获取成功。data → PagedData，content 元素为 ChatSessionVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getChatSessionDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 获取成功。data → ChatSessionDetailVO（含 messages 列表） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteChatSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功。data → null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    sendChatMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSendRequest"];
            };
        };
        responses: {
            /** @description 响应成功。data → ChatReplyVO（JSON）或 SSE 流（text/event-stream） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                    "text/event-stream": string;
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listExerciseQuestions: {
        parameters: {
            query?: {
                subject?: string;
                difficulty?: "EASY" | "MEDIUM" | "HARD";
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 获取成功。data → PagedData，content 元素为 QuestionVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    submitExerciseAnswers: {
        parameters: {
            query?: never;
            header?: {
                /** @description 幂等键（建议 UUID），用于防止重复提交导致的重复写入 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseSubmitRequest"];
            };
        };
        responses: {
            /** @description 提交成功。data → ExerciseResultVO（含逐题判分结果） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getExerciseAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordId: components["parameters"]["RecordId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功。data → ExerciseAnalysisVO（含逐题解析与教师建议） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    listWrongQuestions: {
        parameters: {
            query?: {
                subject?: string;
                status?: "ACTIVE" | "MASTERED";
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功。data → PagedData，content 元素为 WrongBookEntryVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    removeWrongQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 移除成功。data → null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    listExerciseRecords: {
        parameters: {
            query?: {
                startDate?: string;
                endDate?: string;
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功。data → PagedData，content 元素为 ExerciseRecordVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    generateAiQuestions: {
        parameters: {
            query?: never;
            header?: {
                /** @description 幂等键（建议 UUID），用于防止重复提交导致的重复写入 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiQuestionGenerateRequest"];
            };
        };
        responses: {
            /** @description 生成成功。data → AiQuestionGenerateResultVO（含生成题目列表） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    listAiQuestionSessions: {
        parameters: {
            query?: {
                subject?: string;
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功。data → PagedData，content 元素为 AiQuestionSessionVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    submitAiQuestions: {
        parameters: {
            query?: never;
            header?: {
                /** @description 幂等键（建议 UUID），用于防止重复提交导致的重复写入 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiQuestionSubmitRequest"];
            };
        };
        responses: {
            /** @description 提交成功。data → AiQuestionResultVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getAiQuestionAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordId: components["parameters"]["RecordId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功。data → AiQuestionAnalysisVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    listKnowledgeDocuments: {
        parameters: {
            query?: {
                status?: "UPLOADING" | "PARSING" | "EMBEDDING" | "READY" | "FAILED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功。data → DocumentVO 数组 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    uploadKnowledgeDocument: {
        parameters: {
            query?: never;
            header?: {
                /** @description 幂等键（建议 UUID），用于防止重复提交导致的重复写入 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 已接收并进入处理。data → DocumentVO（status=UPLOADING） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    deleteKnowledgeDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功。data → null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    generateLessonPlan: {
        parameters: {
            query?: never;
            header?: {
                /** @description 幂等键（建议 UUID），用于防止重复提交导致的重复写入 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanGenerateRequest"];
            };
        };
        responses: {
            /** @description 生成成功。data → LessonPlanVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    listLessonPlans: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功。data → PagedData，content 元素为 LessonPlanVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    updateLessonPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新成功。data → LessonPlanVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    deleteLessonPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功。data → null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    exportLessonPlan: {
        parameters: {
            query: {
                format: "md" | "pdf";
            };
            header?: never;
            path: {
                planId: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 导出成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    shareLessonPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 生成成功。data → ShareResultVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": 200,
                     *       "message": "success",
                     *       "data": {
                     *         "planId": "00000000-0000-0000-0000-000000000100",
                     *         "shareToken": "abcdef123456",
                     *         "shareUrl": "/api/v1/teacher/plans/shared/abcdef123456"
                     *       },
                     *       "traceId": "trace-xxx",
                     *       "timestamp": "2026-02-26T10:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getSharedLessonPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareToken: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功。data → LessonPlanVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getStudentAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功。data → StudentAnalyticsVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    createTeacherSuggestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherSuggestionRequest"];
            };
        };
        responses: {
            /** @description 创建成功。data → TeacherSuggestionVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                role?: "STUDENT" | "TEACHER" | "ADMIN";
                status?: "ACTIVE" | "DISABLED";
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功。data → PagedData，content 元素为 UserVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserCreateRequest"];
            };
        };
        responses: {
            /** @description 创建成功。data → UserVO */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    patchUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserPatchRequest"];
            };
        };
        responses: {
            /** @description 更新成功。data → UserVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    listResources: {
        parameters: {
            query?: {
                resourceType?: "LESSON_PLAN" | "QUESTION" | "DOCUMENT";
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功。data → PagedData，content 元素为 AdminResourceVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    downloadResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resourceId: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 下载成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    listAudits: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功。data → PagedData，content 元素为 AuditLogVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getAdminDashboardMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功。data → DashboardMetricsVO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
}
