# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in ai_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RagChatServiceStub(object):
    """----------------------------------------
    1. 聊天 RAG 服务 (Chat/RAG)
    ----------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
            "/edunexus.ai.v1.RagChatService/Chat",
            request_serializer=ai__service__pb2.ChatRequest.SerializeToString,
            response_deserializer=ai__service__pb2.ChatResponse.FromString,
            _registered_method=True,
        )
        self.ChatStream = channel.unary_stream(
            "/edunexus.ai.v1.RagChatService/ChatStream",
            request_serializer=ai__service__pb2.ChatRequest.SerializeToString,
            response_deserializer=ai__service__pb2.ChatStreamResponse.FromString,
            _registered_method=True,
        )


class RagChatServiceServicer(object):
    """----------------------------------------
    1. 聊天 RAG 服务 (Chat/RAG)
    ----------------------------------------
    """

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ChatStream(self, request, context):
        """对于支持流式的聊天，可以使用 server-streaming RPC"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RagChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Chat": grpc.unary_unary_rpc_method_handler(
            servicer.Chat,
            request_deserializer=ai__service__pb2.ChatRequest.FromString,
            response_serializer=ai__service__pb2.ChatResponse.SerializeToString,
        ),
        "ChatStream": grpc.unary_stream_rpc_method_handler(
            servicer.ChatStream,
            request_deserializer=ai__service__pb2.ChatRequest.FromString,
            response_serializer=ai__service__pb2.ChatStreamResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "edunexus.ai.v1.RagChatService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "edunexus.ai.v1.RagChatService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RagChatService(object):
    """----------------------------------------
    1. 聊天 RAG 服务 (Chat/RAG)
    ----------------------------------------
    """

    @staticmethod
    def Chat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/edunexus.ai.v1.RagChatService/Chat",
            ai__service__pb2.ChatRequest.SerializeToString,
            ai__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ChatStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/edunexus.ai.v1.RagChatService/ChatStream",
            ai__service__pb2.ChatRequest.SerializeToString,
            ai__service__pb2.ChatStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class ExerciseAnalysisServiceStub(object):
    """----------------------------------------
    2. 错题解析服务 (Exercise Analysis)
    ----------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
            "/edunexus.ai.v1.ExerciseAnalysisService/Analyze",
            request_serializer=ai__service__pb2.ExerciseAnalysisRequest.SerializeToString,
            response_deserializer=ai__service__pb2.ExerciseAnalysisResponse.FromString,
            _registered_method=True,
        )


class ExerciseAnalysisServiceServicer(object):
    """----------------------------------------
    2. 错题解析服务 (Exercise Analysis)
    ----------------------------------------
    """

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ExerciseAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Analyze": grpc.unary_unary_rpc_method_handler(
            servicer.Analyze,
            request_deserializer=ai__service__pb2.ExerciseAnalysisRequest.FromString,
            response_serializer=ai__service__pb2.ExerciseAnalysisResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "edunexus.ai.v1.ExerciseAnalysisService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "edunexus.ai.v1.ExerciseAnalysisService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ExerciseAnalysisService(object):
    """----------------------------------------
    2. 错题解析服务 (Exercise Analysis)
    ----------------------------------------
    """

    @staticmethod
    def Analyze(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/edunexus.ai.v1.ExerciseAnalysisService/Analyze",
            ai__service__pb2.ExerciseAnalysisRequest.SerializeToString,
            ai__service__pb2.ExerciseAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class AiQuestionServiceStub(object):
    """----------------------------------------
    3. AI 个性化出题服务 (AI Question Generator)
    ----------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
            "/edunexus.ai.v1.AiQuestionService/Generate",
            request_serializer=ai__service__pb2.AiQuestionGenerateRequest.SerializeToString,
            response_deserializer=ai__service__pb2.AiQuestionGenerateResponse.FromString,
            _registered_method=True,
        )


class AiQuestionServiceServicer(object):
    """----------------------------------------
    3. AI 个性化出题服务 (AI Question Generator)
    ----------------------------------------
    """

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AiQuestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Generate": grpc.unary_unary_rpc_method_handler(
            servicer.Generate,
            request_deserializer=ai__service__pb2.AiQuestionGenerateRequest.FromString,
            response_serializer=ai__service__pb2.AiQuestionGenerateResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "edunexus.ai.v1.AiQuestionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "edunexus.ai.v1.AiQuestionService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class AiQuestionService(object):
    """----------------------------------------
    3. AI 个性化出题服务 (AI Question Generator)
    ----------------------------------------
    """

    @staticmethod
    def Generate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/edunexus.ai.v1.AiQuestionService/Generate",
            ai__service__pb2.AiQuestionGenerateRequest.SerializeToString,
            ai__service__pb2.AiQuestionGenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class LessonPlanServiceStub(object):
    """----------------------------------------
    4. 教案生成服务 (Lesson Plan Generator)
    ----------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
            "/edunexus.ai.v1.LessonPlanService/Generate",
            request_serializer=ai__service__pb2.LessonPlanGenerateRequest.SerializeToString,
            response_deserializer=ai__service__pb2.LessonPlanGenerateResponse.FromString,
            _registered_method=True,
        )


class LessonPlanServiceServicer(object):
    """----------------------------------------
    4. 教案生成服务 (Lesson Plan Generator)
    ----------------------------------------
    """

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LessonPlanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Generate": grpc.unary_unary_rpc_method_handler(
            servicer.Generate,
            request_deserializer=ai__service__pb2.LessonPlanGenerateRequest.FromString,
            response_serializer=ai__service__pb2.LessonPlanGenerateResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "edunexus.ai.v1.LessonPlanService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "edunexus.ai.v1.LessonPlanService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class LessonPlanService(object):
    """----------------------------------------
    4. 教案生成服务 (Lesson Plan Generator)
    ----------------------------------------
    """

    @staticmethod
    def Generate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/edunexus.ai.v1.LessonPlanService/Generate",
            ai__service__pb2.LessonPlanGenerateRequest.SerializeToString,
            ai__service__pb2.LessonPlanGenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class KnowledgeBaseServiceStub(object):
    """----------------------------------------
    5. 知识库服务 (Knowledge Base)
    ----------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ingest = channel.unary_unary(
            "/edunexus.ai.v1.KnowledgeBaseService/Ingest",
            request_serializer=ai__service__pb2.KbIngestRequest.SerializeToString,
            response_deserializer=ai__service__pb2.KbIngestResponse.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/edunexus.ai.v1.KnowledgeBaseService/Delete",
            request_serializer=ai__service__pb2.KbDeleteRequest.SerializeToString,
            response_deserializer=ai__service__pb2.KbDeleteResponse.FromString,
            _registered_method=True,
        )


class KnowledgeBaseServiceServicer(object):
    """----------------------------------------
    5. 知识库服务 (Knowledge Base)
    ----------------------------------------
    """

    def Ingest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_KnowledgeBaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Ingest": grpc.unary_unary_rpc_method_handler(
            servicer.Ingest,
            request_deserializer=ai__service__pb2.KbIngestRequest.FromString,
            response_serializer=ai__service__pb2.KbIngestResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=ai__service__pb2.KbDeleteRequest.FromString,
            response_serializer=ai__service__pb2.KbDeleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "edunexus.ai.v1.KnowledgeBaseService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "edunexus.ai.v1.KnowledgeBaseService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class KnowledgeBaseService(object):
    """----------------------------------------
    5. 知识库服务 (Knowledge Base)
    ----------------------------------------
    """

    @staticmethod
    def Ingest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/edunexus.ai.v1.KnowledgeBaseService/Ingest",
            ai__service__pb2.KbIngestRequest.SerializeToString,
            ai__service__pb2.KbIngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/edunexus.ai.v1.KnowledgeBaseService/Delete",
            ai__service__pb2.KbDeleteRequest.SerializeToString,
            ai__service__pb2.KbDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
